name: planificador-turnos-api

services:
- name: web
  source_dir: /
  github:
    branch: main
    deploy_on_push: true
  run_command: gunicorn --bind=0.0.0.0:$PORT api:app
  environment_slug: python
  instance_count: 1
  instance_size_slug: basic-xxs
  http_port: 8080
  health_check:
    http_path: "/health"